# Generated by Django 5.2.9 on 2025-12-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_refreshtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refreshtoken',
            table='university_refreshtoken',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.DecimalField(decimal_places=2, help_text='Grade value (0-100)', max_digits=5)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the grade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to='university.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject', 'professor')},
            },
        ),
    ]
